name: On push pipeline
on:
  push:
    branches-ignore:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Code Check
        run: ./gradlew --no-daemon clean check
